### ISSUE TITLE
Long time no start

### ISSUE THREAD

**Issue by Mavourn3en** [lbfs/DeepFaceLab_Linux#10]
It's still pretty slow when training. I kept waiting for almost half an hour but it still didn't start to train with preview window, However, it works well without preview.

Ubuntu 18.04

Looking forward to seeing new updates to solve this problem^_^

**Comment by lbfs** [comment]
Can you tell me what your system specifications are? I've been unable to replicate this problem to the extent others are having. I did notice a performance regression on newer builds, but it still starts testing fairly quickly. 

Can you also tell me what model settings you are trying to use?

**Comment by lbfs** [comment]
If you can look in the column ``ni`` in ``top`` and tell me what the value of Python3.6 is when waiting for training to start, I may have an idea on what is causing this.

**Comment by lbfs** [comment]
Using Console
Loading: 100%|#############################| 1500/1500 [00:02<00:00, 539.75it/s]
Loading: 100%|#############################| 1445/1445 [00:02<00:00, 696.87it/s]

Using GUI

Using TensorFlow backend.
Loading: 100%|##############################| 1500/1500 [00:18<00:00, 82.50it/s]
Loading: 100%|##############################| 1445/1445 [00:17<00:00, 81.78it/s]

Able to replicate

**Comment by lbfs** [comment]
@Mavourn3en 
I have a temporary fix that I wish you to test
Can you checkout the cv2waitkeyfix branch and let me know what the results are? I've noticed a massive increase in speed

``git checkout cv2waitkeyfix``

**Comment by Mavourn3en** [comment]
> @Mavourn3en
> I have a temporary fix that I wish you to test
> Can you checkout the cv2waitkeyfix branch and let me know what the results are? I've noticed a massive increase in speed
> 
> `git checkout cv2waitkeyfix`
OK, I'm going to test it. Once I have any results, I will report in time.

**Comment by Mavourn3en** [comment]
> Can you tell me what your system specifications are? I've been unable to replicate this problem to the extent others are having. I did notice a performance regression on newer builds, but it still starts testing fairly quickly.
> 
> Can you also tell me what model settings you are trying to use?
> Also, installation method may be useful knowledge.
> 
> Also make sure you're using the latest commit, we fixed a bug related to multiprocess and it may have fixed other performance issues.

**Comment by Mavourn3en** [comment]
OS: Ubuntu 18.04.2 LTS
RAM: 16GB
CPU: Intel® Core™ i7-8750H CPU @ 2.20GHz × 12 
GPU: GeForce GTX 1070 With Max-Q Design(driver version 390.116)

Anaconda: Anaconda3-5.3.1-Linux-x86_64.sh from https://mirrors.tuna.tsinghua.edu.cn/anaconda/archive/
Installed following README.md

I was trying to train with SAE, BS was 16, Optimizer mode was 2 and resolution 256, others were default.

**Comment by Mavourn3en** [comment]
@lbfs 
Your test version works very well. The TensorFlow process runs immediately right after I finish setting and the preview window shows up.
Good job, Dude.
^_^

**Comment by lbfs** [comment]
I'm glad, I'll have to do more investigative work to figure out the root problem though, but I'm glad this will work temporarily.

**Comment by lbfs** [comment]
@iperov

A possible performance but that may also exist on Windows, but I'm unsure since I don't have that platform, thoughts?

Before temporary fix (Program may take up to a minute to launch; others more)
```
Using GUI
Loading: 100%|##############################| 1500/1500 [00:18<00:00, 82.50it/s]
Loading: 100%|##############################| 1445/1445 [00:17<00:00, 81.78it/s]

Using No Preview
Loading: 100%|#############################| 1500/1500 [00:02<00:00, 539.75it/s]
Loading: 100%|#############################| 1445/1445 [00:02<00:00, 696.87it/s]
```

After temporary fix (Program launches almost immediately after putting in config options)
```
Using GUI
Loading: 100%|#############################| 1500/1500 [00:02<00:00, 558.55it/s]
Loading: 100%|#############################| 1445/1445 [00:01<00:00, 728.75it/s]

Using Console
Loading: 100%|#############################| 1500/1500 [00:02<00:00, 557.86it/s]
Loading: 100%|#############################| 1445/1445 [00:01<00:00, 731.28it/s]
```

The temporary fix that isn't the best solution is here
https://github.com/lbfs/DeepFaceLab_Linux/commi/7eab59bfd9c1ce7c573d27dc486ae47ccb978229

**Comment by iperov** [comment]
try last dfl commit

**Comment by iperov** [comment]
ah no, wait

**Comment by iperov** [comment]
now check

**Comment by lbfs** [comment]
Program performance seems even slower now, I've been stuck on Using Tensorflow Backend for >2 minutes.

**Comment by iperov** [comment]
wrong test

**Comment by iperov** [comment]
performance cannot be slower in last commit

**Comment by lbfs** [comment]
After rebooting my system; seems to be identical performance

```bash
ubuntu@deepfacelab:/mnt/secondary/DeepFaceLab/scripts$ git log | head -n 5
commit a8c987fa0f3af0b4cd2e7d471b5ff9153c4d30ea
Author: iperov <lepersorium@gmail.com>
Date:   Fri Mar 15 11:50:13 2019 +0400

    fix performance issue
ubuntu@deepfacelab:/mnt/secondary/DeepFaceLab/scripts$ ./6_train_H64.sh
Running trainer.

Loading model...
Press enter in 2 seconds to override model settings.Using TensorFlow backend.
Loading: 100%|##############################| 1500/1500 [00:20<00:00, 72.07it/s]
Loading: 100%|################################| 548/548 [00:06<00:00, 86.64it/s]
===== Model summary =====
== Model name: H64
==
== Current iteration: 196
==
== Model options:
== |== write_preview_history : True
== |== batch_size : 4
== |== sort_by_yaw : False
== |== random_flip : True
== |== lighter_ae : False
== |== pixel_loss : False
== Running on:
== |== [0 : GeForce GTX 1070 Ti]
=========================
Starting. Press "Enter" to stop training and save model.

ubuntu@deepfacelab:/mnt/secondary/DeepFaceLab/scripts$ ./6_train_H64_no_preview.sh
Running trainer.

Loading model...
Press enter in 2 seconds to override model settings.Using TensorFlow backend.
Loading: 100%|#############################| 1500/1500 [00:02<00:00, 595.88it/s]
Loading: 100%|###############################| 548/548 [00:00<00:00, 753.80it/s]
===== Model summary =====
== Model name: H64
==
== Current iteration: 196
==
== Model options:
== |== write_preview_history : True
== |== batch_size : 4
== |== sort_by_yaw : False
== |== random_flip : True
== |== lighter_ae : False
== |== pixel_loss : False
== Running on:
== |== [0 : GeForce GTX 1070 Ti]
=========================
Starting. Press "Enter" to stop training and save model.

```

**Comment by iperov** [comment]
cv2.waitKey(100)
is same as
process_messages(0.1)

**Comment by iperov** [comment]
```
if has_windows or has_capture_keys:
            wait_key_time = max(1, int(sleep_time*1000) )
            key = cv2.waitKey(wait_key_time) & 0xFF
        else:
            if sleep_time != 0:
                time.sleep(sleep_time)
```

**Comment by lbfs** [comment]
See thats what I thought because I tried making a similar fix to that, but it didn't do much.

**Comment by iperov** [comment]
if you think preview decrease performance
then dont start trainer
```
#thread = threading.Thread(target=trainerThread, args=(s2c, c2s, args, device_args) )
#thread.start()
```
and check load

**Comment by iperov** [comment]
anyway all fine in windows.

**Comment by lbfs** [comment]
Alright, I'll look around and see if I find anything. I didn't see any issues on this on your repo which Is why I assumed it to be Linux only, but had to ask to make sure.

**Comment by iperov** [comment]
this is why I dont like linux. A lot of hidden problems.

**Comment by lbfs** [comment]
True Indeed.

**Comment by lbfs** [comment]
I think I've attributed this bug to the fact that there is a busy wait occuring
https://github.com/lbfs/DeepFaceLab_Linux/commit/a869e9fc35023dccad9c9ee1d66816c9fc1fa1d3
I've set up a signal to start the GUI process once the training thread is ready, and this has seemed to fix the issue. 

However, this probably means the issue occurs in other parts of the program, specifically the manual extractor, so I'll need to look at those
