### ISSUE TITLE
write preview history

### ISSUE THREAD

**Issue by coinsbarboss** [lbfs/DeepFaceLab_Linux#13]
I noticed a strange behavior of this option "write preview history".

With an iteration number growing during the training process, it keeps recording the **SAME** preview image, which is actually very outdated.

I think it's a bug, but unfortunately my knowledge doesnt allow me to find the reason.
That option _(to save previews)_ is very important for me, as my server doesnt have a monitor, so I'm forced to use **--no-preview training**

Hope for your help.

**Comment by lbfs** [comment]
This isn't a bug, write preview history uses the same set of images to show how the model is evolving over time. Comparing an early iteration to an iteration done after hours of training should yield different results, but have the same photos. 

The GUI application will show you different previews based on different source/destination images, and I may have to look into a way to add a rotate feature like that to the options.
