### ISSUE TITLE
Could not create cudnn handle：CUDNN_STATUS_INTERNAL_ERROR.

### ISSUE THREAD

**Issue by Nostalgia1990** [lbfs/DeepFaceLab_Linux#14]
After the screen showing that 'starting,Press 'Enter' to stop training and save model',an erro happened——

Could not create cudnn handle：CUDNN_STATUS_INTERNAL_ERROR.

## Other relevant information
- **Command lined used (if not specified in steps to reproduce)**: main.py ...
- **Operating system and version:** CentOS Linux 
- **Python version:** 3.6, ... (if you are not using prebuilt windows binary)
- **CUDA:**  9.0,
- **cudnn:**  7,
- **tensorflow-gpu:** 1.12.0,

**Comment by lbfs** [comment]
I need to know your video driver version and graphics card.

**Comment by Nostalgia1990** [comment]
> I need to know your video driver version and graphics card.

2 Tesla V100 and 4 Tesla k80,  nvidia driver version is 384.145

**Comment by lbfs** [comment]
Install method?

**Comment by Nostalgia1990** [comment]
> Install method for DeepFaceLab?
because my linux is CentOS ,so the method for ubuntu may not works.

The difference between them is great.

can you write a guide for centos? thank you!

**Comment by lbfs** [comment]
Try Anaconda3 install method, it is not distro dependent.

**Comment by Nostalgia1990** [comment]
> Try Anaconda3 install method, it is not distro dependent.


please give me the web link for detailed anaconda3 methond,Thank you.

And the anaconda3 is installed on my OS ,the Version is for python 3.6.

**Comment by lbfs** [comment]
I don't know how to help you. I may create native instructions for CentOS in the future, but currently I do not support this. The instructions are listed in the README.md for Anaconda3, if that method does not work, you can try translating the instructions from the Ubuntu install script to CentOS to allow it to work on your platform.
