### ISSUE TITLE
Training FAN model is different from Windows version

### ISSUE THREAD

**Issue by coinsbarboss** [lbfs/DeepFaceLab_Linux#16]
Hi,

For some reason, FAN model which were trained on Windows does not work on Linux.

Is it possible to fix that?

**Comment by lbfs** [comment]
Are you on the latest branch and can you tell me what exactly is different? I'll look into this soon.

**Comment by coinsbarboss** [comment]
After upgrading to the latest - model name is "FANSeg", which is the same as Windows version.

Thanks!
