### ISSUE TITLE
no AMD/OpenCL installation instructions/scripts?

### ISSUE THREAD

**Issue by dchmelik** [lbfs/DeepFaceLab_Linux#18]
Your installation instructions/scripts are only for Nvidia but I'm aware setup is possible with AMD/OpenCL display/video/graphic cards.  Will that be documented or have scripts made?

**Comment by lbfs** [comment]
I believe you can install ``requirements-opencl.txt`` instead of ``requirements-cuda.txt``. You need to also run plaidml-setup on Linux. Otherwise, the scripts should work as intended. At least for the Anaconda installation.

**Comment by lbfs** [comment]
DeepFaceLab appears to have dropped OpenCL and CPU support to some extent, so this is really no longer viable.
