### ISSUE TITLE
Problem with start train on linux server

### ISSUE THREAD

**Issue by good-mouse** [lbfs/DeepFaceLab_Linux#19]
Have problem with start train on linux server
Work on ssh
After run script bash 6_train_Quick96.sh i have error:
cannot connect to X server

**Comment by lbfs** [comment]
Try the most recent commit and use 6_train_Quick96_no_preview.sh instead.

**Comment by good-mouse** [comment]
> Try the most recent commit and use 6_train_Quick96_no_preview.sh instead.

tnx a lot, it works now
