### ISSUE TITLE
mac

### ISSUE THREAD

**Issue by oracle9i88** [lbfs/DeepFaceLab_Linux#2]
does mac 10.13 can use opencl version?

**Comment by lbfs** [comment]
Do you have a Mac we could potentially try this on? My Mac doesn't have a GPU with a high enough OpenCL version so I've been unable to test this.

**Comment by lbfs** [comment]
I already have a limited ability to test Mac OS and with the recent updates to use newer versions of Tensorflow and CUDA I cannot see me being able to support this further. Sorry.
