### ISSUE TITLE
Bug with choosing gpu

### ISSUE THREAD

**Issue by good-mouse** [lbfs/DeepFaceLab_Linux#21]
I choose gpu 0 indx but work started on all my cpu cores

- cuda == 9.0
- cudnn == 7.6.4
- tensorflow == 1.13.2
- tensorflow-gpu ==1.13.2

![](https://user-images.githubusercontent.com/24617421/74919915-5c9e2500-53dc-11ea-83bb-37016fb79a3f.png)

**Training works on gpu fine**

**Comment by lbfs** [comment]
This might be related to the other issue posted, but I'm not positive. I'll investigate during the weekend.

**Comment by iperov** [comment]
model runs on GPU

merger runs on CPU
