### ISSUE TITLE
OOM when allocating tensor

### ISSUE THREAD

**Issue by good-mouse** [lbfs/DeepFaceLab_Linux#22]
Similar issue:  [link](https://github.com/lbfs/DeepFaceLab_Linux/issues/7)

<img width="1313" alt="Снимок экрана 2020-02-21 в 12 02 29" src="https://user-images.githubusercontent.com/24617421/75019527-16ab9480-54a2-11ea-8fe7-ce81c117d862.png">

cuda == 9.0
cudnn == 7.6.4
tensorflow == 1.13.2
tensorflow-gpu ==1.13.2

run train SAEHD script, train Quick96 works fine

**Comment by lbfs** [comment]
Change your settings to be less intensive. This isn't a bug.
