### ISSUE TITLE
Simplify the fork?

### ISSUE THREAD

**Issue by iperov** [lbfs/DeepFaceLab_Linux#23]
can your fork be simplified like https://github.com/elemantalcode/dfl by @elemantalcode ?

are there any specific linux changes in your fork?

**Comment by lbfs** [comment]
I think it can be and that's probably the best course of action. The only Linux specific change I can think of is in the VideoEd.py where I allow experimental options to deal with older ffmpeg versions. I can look into simplifying it later tonight.

**Comment by iperov** [comment]
```
output_kwargs.update ({"c:a": "aac",
                               "b:a": "192k",
                            "b:a": "192k",
                               "ar" : "48000"
                            "ar" : "48000",
                               })
                            "strict": "experimental"
                            })
```

what does 'strict' do ?
Can I set it for windows ffmpeg?

**Comment by lbfs** [comment]
You should be able to set it for windows without issue. Ubuntu 16.04 has an older version of ffmpeg where common video codecs now we're still experimental.

**Comment by lbfs** [comment]
Done.

**Comment by iperov** [comment]
I changed to "strict": "experimental"
