### ISSUE TITLE
Running on CPU instead of GPU

### ISSUE THREAD

**Issue by theinterestingstory** [lbfs/DeepFaceLab_Linux#25]
I know this isn't strictly about this repo, but I wasn't sure where else to ask.

I posted here about my issue, however, the owner doesn't support linux. Does anyone know what could be wrong with my setup?

https://github.com/iperov/DeepFaceLab/issues/643

Thank you!

**Comment by lbfs** [comment]
Follow my installation instructions exactly to the letter and let me know how it works. I'm not going to diagnose an installation that isn't properly setup.

**Comment by theinterestingstory** [comment]
Yeah, it works fine with your setup. Even though I do the same thing when outside of anaconda, it doesn't work. Idk, man. It's not your problem. I'll figure it out, thanks.
