### ISSUE TITLE
mac 10.13 stuck in...

### ISSUE THREAD

**Issue by oracle9i88** [lbfs/DeepFaceLab_Linux#6]
/Users/oracle9i/anaconda3/envs/deepfacelab/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2019-03-08 15:29:22.976405: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Using TensorFlow backend.
WARNING:tensorflow:From /Users/oracle9i/anaconda3/envs/deepfacelab/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
Loading: 100%|################################| 137/137 [00:02<00:00, 49.31it/s]
Loading: 100%|##################################| 28/28 [00:00<00:00, 49.41it/s]

#####stuck in here

**Comment by oracle9i88** [comment]
(deepfacelab) oracle9is-MBP:DeepFaceLab_Linux oracle9i$ python main.py train --training-data-src-dir workspace/data_src/aligned --training-data-dst-dir workspace/data_dst/aligned --model-dir model --model H128
plaidML: No capable OpenCL devices found. Falling back to tensorflow backend.
Running trainer.

Loading model...

Model first run. Enter model options as default for each run.
Write preview history? (y/n ?:help skip:n/default) :

**Comment by lbfs** [comment]
Again.. OpenCL was deprecated on Mac OS and I'm no longer supporting this due to the tensorflow-gpu upgrade which further breaks compatibility. Sorry.
