### ISSUE TITLE
Error: OOM when allocating tensor with shape

### ISSUE THREAD

**Issue by tetli** [lbfs/DeepFaceLab_Linux#7]
ALSO POSTED IN MAIN REPO
Could the issue be specific for running it virtually (source activate deepfacelab) with this fork?

Similar issue: https://github.com/iperov/DeepFaceLab/issues/119

I get `Error: OOM when allocating tensor with shape` when running the train models (`6_train_H64.sh`and `6_train_128.sh`, same with the "no-preview" versions). 

@iperov suggested in the example above of using to use the lightweight encoder and a very small batch size. I've tried many different batch-sizes, with and without lightweight auto-encoder, both with the H64 and H128. I get the same issue even when running lightweight with a batch size of 2. 

IMPORTANT: I run this on the **Linux-fork** (https://github.com/lbfs/DeepFaceLab_Linux) on a **Quadro P5000 (16 GB)** on a **Linux ML-in-a-Box Paperspace** configuration.

Any idea what the problem could be?
I can't imagine that the lack of VRAM is the actual issue with his card.

<img width="1350" alt="Screenshot 2019-03-12 at 13 40 42" src="https://user-images.githubusercontent.com/31843785/54201816-e2c4a280-44ce-11e9-9f90-0aea5580882b.png">

**Comment by lbfs** [comment]
Are you running Ubuntu 16.04; Ubuntu 14.04; or Ubuntu 18.04?
What video driver do you currently have installed?

**Comment by lbfs** [comment]
I am unable to replicate this issue with my GTX 1070 Ti.

**Comment by lbfs** [comment]
If possible, I also need to see the output of ``nvcc -V``

**Comment by lbfs** [comment]
@tetli hello?

**Comment by lbfs** [comment]
No response from user.
