### ISSUE TITLE
Why is the initialization very slow when training？

### ISSUE THREAD

**Issue by deyu260** [lbfs/DeepFaceLab_Linux#8]
Why is the initialization very slow when training, it takes about an hour to train and pop up the preview window. Restarting the computer does not solve the problem. I used the anconda version 3.5.2 and followed the readme.md.

os ubuntu 18.04.2
nvidia driver 415
cpu e3 1230v2 
motherboard Gigabyte h67MA-USB3
graphics card rx578 + p106-100 6g
ram 4Gx2

**Comment by lbfs** [comment]
I'm still looking into this and I'm not exactly sure what is causing it. I'm suspecting something to do with the fact we recently upgraded to Tensorflow 1.12

**Comment by lbfs** [comment]
Can you do a ``git pull`` and then ``git checkout processprio``? I've reverted one of the changes made and it should fix the slowness. Let me know if it fixes the problem

**Comment by lbfs** [comment]
I believed I fixed this with the recent commit, if you still have further issues feel free to respond, but for now I'm closing this.

**Comment by lbfs** [comment]
@deyu260 fixed https://github.com/lbfs/DeepFaceLab_Linux/commit/7eab59bfd9c1ce7c573d27dc486ae47ccb978229
